# Generated by Django 3.0.7 on 2020-06-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_2018', models.URLField()),
                ('_2019', models.URLField()),
                ('_2020', models.URLField()),
            ],
        ),
    ]
