# Generated by Django 3.0.7 on 2020-06-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasury',
            name='_2018',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='_2019',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='_2020',
            field=models.CharField(max_length=5000),
        ),
    ]
