# Generated by Django 3.0.7 on 2020-06-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20200619_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasury',
            old_name='_2018',
            new_name='year18',
        ),
        migrations.RenameField(
            model_name='treasury',
            old_name='_2019',
            new_name='year19',
        ),
        migrations.RenameField(
            model_name='treasury',
            old_name='_2020',
            new_name='year20',
        ),
    ]
